#!/bin/bash

nproc="$(/usr/bin/nproc)"

source /lib/gentoo/functions.sh

for repo in local haskell; do
	einfo "Running egencache for $repo"
	if ! egencache --update "-j${nproc}" --load-average "${nproc}.0" --repo "$repo"
	then
		eerror "egencache failed!"
		exit 1
	fi
done
