#!/bin/bash

source /lib/gentoo/functions.sh


for repo in local local-haskell; do

	einfo "Running egencache for $repo"

	if ! egencache --update -j4 --load-average 4.0 --repo "$repo"
		then
		eerror "egencache failed!"
		exit 1
	fi
