#!/bin/bash

source /lib/gentoo/functions.sh

repository_name=${1}


if [[ -n "${repository_name}" ]]; then
	[[ "${repository_name}" == "gentoo" ]] && exit 0
	
	einfo "Running egencache for $repository_name"

	if ! egencache --update -j6 --load-average 6.0 --repo "$repository_name"
	then
		eerror "egencache failed!"
		exit 1
	fi
fi
