#!/bin/bash

source /lib/gentoo/functions.sh

nproc="$(/usr/bin/nproc)"
repo="$1"


if [[ -n "$repo" ]]; then
	[[ "$repo" == "gentoo" ]] && exit 0
	
	einfo "Running egencache for $repo"

	if ! egencache --update "-j${nproc}" --load-average "${nproc}.0" --repo "$repo"
	then
		eerror "egencache failed!"
		exit 1
	fi
else
	einfo "$0 ran with no argument"
fi
